//! Enables compile-time separation of tags from different managers.

#[cfg(doc)]
use crate::generate_label;
#[cfg(doc)]
use crate::storage::Storage;
#[cfg(doc)]
use crate::tag::Tag;
#[cfg(doc)]
use crate::TagManager;

/// A type for compile-time separation of [`Tag`]s from different [`TagManager`]s.
///
/// This enables the compile-time guarantee that a [`Tag`] generated by one
/// [`TagManager`] is never resolved through another [`TagManager`] (which might
/// succeed but produce incorrect or nonsensical results at runtime if permitted).
///
/// # Not `unsafe`
///
/// This used to be an `unsafe` trait, hinting at an obligation it never quite had: that a
/// label be used with only one interner. Nothing about implementing it could break a
/// safety guarantee, and the obligation it gestured at is now [`Storage`]'s brand, which
/// enforces it at compile time rather than asking implementors to be careful. So the trait
/// is safe, and [`generate_label`] is a convenience rather than a safety measure.
///
/// A label is never instantiated, so a zero-sized type is the sensible choice, which is
/// what [`generate_label`] produces.
///
/// # `Send` and `Sync`
///
/// [`Label`]s are required to be [`Send`] and [`Sync`] so that the types carrying
/// them as [`PhantomData`] — parsers, tags, and [`Storage`] — are too, without
/// each of those needing a hand-written `unsafe impl` or every generic function
/// over a label having to repeat the bounds. Since a label is never instantiated,
/// and is a zero-sized type by convention, this costs nothing: every label built
/// by [`generate_label`] satisfies it automatically.
///
/// [`PhantomData`]: std::marker::PhantomData
pub trait Label: Copy + Send + Sync {}

/// Generate a new type implementing [`Label`].
///
/// # Example
///
/// ```
/// # use tagbuddy::generate_label;
///
/// generate_label! {
///     /// Tags used for blog posts in this blog implementation.
///     pub BlogPostTags {}
/// }
/// ```
#[macro_export]
macro_rules! generate_label {
    ( $( $( #[$($attrss:meta)*] )* $visibility:vis $struct_name:ident {} )* ) => {
        $(
            $crate::generate_label! { @single $( #[$($attrss)*] )* $visibility $struct_name {} }
        )*
    };

    ( @single $( #[$($attrss:meta)*] )* $visibility:vis $struct_name:ident {} ) => {
        $( #[$($attrss)*] )*
        #[derive(Debug, Copy, Clone)]
        $visibility struct $struct_name;
        impl $crate::label::Label for $struct_name {}
    };
}

generate_label! {
    /// The default label applied when no other label is provided.
    pub DefaultLabel {}
}
